[Complete][Phase1]
deepgram-devs/deepgram-ai-agent-demo pull request #57
Opened 2024-09-06 07:31 UTC by TechAlchemy423

2024-09-06 07:37 UTC, TechAlchemy423 commented
**- should use these environmental variables in your .env file.**

  DEEPGRAM_STT_DOMAIN=https://api.deepgram.com/
  DEEPGRAM_SOCKET_URL=wss://sts.sandbox.deepgram.com/agent
  DEEPGRAM_API_KEY=b6f78efae4b2128e4c3d8f81fb6c740b8c0bc077
  DEEPGRAM_ENV=development
  JWT_SECRET=my-secret
  NEXT_PUBLIC_DEEPGRAM_SOCKET_URL=wss://sts.sandbox.deepgram.com/agent
  NEXT_PUBLIC_DEEPGRAM_API_KEY=b6f78efae4b2128e4c3d8f81fb6c740b8c0bc077
  
 **- The UI is changed from original UI cuz of using Agent API. So plz check the UI and if you want to maintain original UI, it will take  2 days.**
 
 **- I counted time for this work as 40 hrs.**
 
 This is Deepgram project and I need to read Deepgrap  documentation to get clear understand about this API logic and integration police 

Previously I do not know about this Deepgrap because it is not a popular framwork like React.js or Next.js. This Deepgram is needed only for this project So I  took some time like 2 days extra for learning. Because I work and read this documentation that I needed to work . 

It is take only 4/5 days But I take some extra for this reason.

2024-09-13 11:08 UTC, lukeocodes requested changes

2024-09-13 11:08 UTC, lukeocodes commented on package.json
@ricky0123/vad-react, onnxruntime-web and openai should all have been removed by now

2024-09-13 11:08 UTC, lukeocodes commented on app/lib/constants.ts
> +export const voices: {
Remove these options, keep the app simple for now

2024-09-13 11:08 UTC, lukeocodes commented on app/lib/constants.ts
> +export const models = [
Remove these too, we keep it very simple

2024-09-13 11:08 UTC, lukeocodes commented on app/components/Conversation.tsx
This file isn't even used anymore

2024-09-21 11:52 UTC, lukeocodes approved these changes

2024-09-21 11:53 UTC, merged